name: i_updater
description: "A Flutter plugin for managing in-app updates seamlessly, ensuring users always have the latest version of your app with minimal hassle."
version: 0.0.5
homepage: https://github.com/iwalletmobilecase/i_updater
repository: https://github.com/iwalletmobilecase/i_updater
documentation: https://github.com/iwalletmobilecase/i_updater
issue_tracker: https://github.com/iwalletmobilecase/i_updater/issues
topics:
  - updater
  - force-update
  - mandatoriy-update
  - update-management
  - app-updater

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tr.com.iwallet.i_updater
        pluginClass: IUpdaterPlugin
      ios:
        pluginClass: IUpdaterPlugin
